from tkinter import *
from tkinter import messagebox
from tkinter import ttk
master = Tk()
master.title(&#39;tk&#39;)
Label(master,text=&#39;CAR RENTAL RECEIPT&#39;).grid(row=0,column=2)
Label(master, text=&#39;Date&#39;).grid(row=2)
Label(master,text=&#39;Receipt#&#39;).grid(row=3)
Label(master, text=&#39;Rental Company Info &#39;).grid(row=4)
Label(master,text=&#39;Company:&#39;).grid(row=5)
Label(master, text=&#39;Representatives:&#39;).grid(row=6)
Label(master, text=&#39;Location:&#39;).grid(row=7)
Label(master, text=&#39;City State/ZIP:&#39;).grid(row=8)
Label(master,text=&#39;Phone:&#39;).grid(row=9)
Label(master, text=&#39;Lessee Info &#39;).grid(row=4,column=2)
Label(master,text=&#39;Name:&#39;).grid(row=5,column=2)
Label(master, text=&#39;License #: &#39;).grid(row=6,column=2)
Label(master,text=&#39;Address:&#39;).grid(row=7,column=2)
Label(master, text=&#39;City/state/ZIP:&#39;).grid(column=2,row=8)
Label(master, text=&#39;Phone: &#39;).grid(column=2,row=9)
Label(master,text=&#39;VEHICLE INFORMATION&#39;).grid(row=10,column=2)
Label(master, text=&#39;VIN: &#39;).grid(row=11)
Label(master,text=&#39;Make:&#39;).grid(row=12)
Label(master, text=&#39;Year:&#39;).grid(row=13)
Label(master, text=&#39;Color:&#39;).grid(row=14)
Label(master, text=&#39;Registration #&#39;).grid(row=11,column=2)
Label(master,text=&#39;Model:&#39;).grid(row=12,column=2)
Label(master, text=&#39;Mileage:&#39;).grid(row=13,column=2)
Label(master, text=&#39;VIN&#39;).grid(row=15,column=0)
Label(master, text=&#39;Cost/Day&#39;).grid(row=15,column=1)
Label(master, text=&#39;# ofDays&#39;).grid(row=15,column=2)
Label(master, text=&#39;Aditional Costs&#39;).grid(row=15,column=3)
Label(master, text=&#39;Line Total&#39;).grid(row=15,column=4)
Label(master, text=&#39;Subtotal:&#39;).grid(row=19,column=3)
Label(master, text=&#39;Tax{%}:&#39;).grid(row=20,column=3)
Label(master, text=&#39;Total:&#39;).grid(row=21,column=3)
Label(master, text=&#39;Amount Paid:&#39;).grid(row=22,column=3)
Label(master, text=&#39;Payment Method:&#39;).grid(row=19,column=0)
Label(master,text=&#39;Authorized Signature:&#39;).grid(row=25,column=3)
Label(master,text=&#39;Representative Name:&#39;).grid(row=26,column=3)
e1 = Entry(master).grid(row=2,column=1)
e12=Entry(master).grid(row=3,column=1)
e2 =Entry(master).grid(row=5,column=1)
e3 =Entry(master).grid(row=6,column=1)
e4 =Entry(master).grid(row=7,column=1)
e5 =Entry(master).grid(row=8,column=1)
e6 =Entry(master).grid(row=9,column=1)
e7=Entry(master).grid(row=5,column=3)
e8=Entry(master).grid(row=6,column=3)

e9=Entry(master).grid(row=7,column=3)
e10=Entry(master).grid(row=8,column=3)
e11=Entry(master).grid(row=9,column=3)
e12=Entry(master).grid(row=11,column=1)
e13=Entry(master).grid(row=12,column=1)
e14=Entry(master).grid(row=13,column=1)
e15=Entry(master).grid(row=14,column=1)
e16=Entry(master).grid(row=11,column=3)
e17=Entry(master).grid(row=12,column=3)
e18=Entry(master).grid(row=13,column=3)
e19=Entry(master).grid(row=16,column=0)
e20=Entry(master).grid(row=16,column=1)
e21=Entry(master).grid(row=16,column=2)
e22=Entry(master).grid(row=16,column=3)
e23=Entry(master).grid(row=16,column=4)
e24=Entry(master).grid(row=17,column=0)
e25=Entry(master).grid(row=17,column=1)
e26=Entry(master).grid(row=17,column=2)
e27=Entry(master).grid(row=17,column=3)
e28=Entry(master).grid(row=17,column=4)
e29=Entry(master).grid(row=18,column=0)
e30=Entry(master).grid(row=18,column=1)
e31=Entry(master).grid(row=18,column=2)
e32=Entry(master).grid(row=18,column=3)
e33=Entry(master).grid(row=18,column=4)
e34=Entry(master).grid(row=19,column=4)
e35=Entry(master).grid(row=20,column=4)
e36=Entry(master).grid(row=21,column=4)
e37=Entry(master).grid(row=22,column=4)
e38=Entry(master).grid(row=20,column=2)
e39=Entry(master).grid(row=21,column=1)
e40=Entry(master).grid(row=22,column=1)
e41=Entry(master).grid(row=25,column=4)
e42=Entry(master).grid(row=26,column=4)
var3 = IntVar()
Checkbutton(master, text=&quot;Cash:&quot;,variable=var3).grid(row=20,
column=0)
var4 = IntVar()
Checkbutton(master, text=&quot;Check No:&quot;,variable=var4).grid(row=20,
column=1)
var5 = IntVar()
Checkbutton(master, text=&quot;Credit No:&quot;,variable=var5).grid(row=21,
column=0)
var6 = IntVar()
Checkbutton(master, text=&quot;Other:&quot;,variable=var6).grid(row=22,
column=0)
master.mainloop()